/**********************************************************************************************************************
 * \file xDebug.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef APP_INC_XDEBUG_H_
#define APP_INC_XDEBUG_H_

#ifndef EXTERN
#define EXTERN extern
#endif

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

#define debAPPLICATION_PFLS_ADDR    ( ( 0xA0100000UL ) + ( 0x20UL ) )
#define candyRCVD_BUFF_NUM          5
#define candySENT_BUFF_NUM          15

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 typedef struct DEBUG_PORT_CONFIG
{
    u32 xPort;
    u32 xIndex;
} DbgPortCfg_t;

typedef struct CANDY_PAK_102
{
    uint8 rgucSeq[3];
    uint8 rgucPayload[5];
} CandyPak102_t;

typedef struct CANDY_DATA_FRAME
{
    Can_IdType CanId;
    uint8 CanDlc;
    uint8 CanSdu[8];
} CandyFrame_t;

typedef struct CANDY_RECEIVED_STRUCTURE
{
    BaseType_t xUsed;
    TickType_t xRcvdTick;
    CandyFrame_t xCandy;
} CandyRcvd_t;

typedef struct CANDY_DESCRIPTOR_STRUCTURE
{
    BaseType_t xNextIndx;
    CandyFrame_t rgxSent[candySENT_BUFF_NUM];
    CandyRcvd_t rgxRcvd[candyRCVD_BUFF_NUM];
} CandyDescr_t;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void vStartDebugTask( char *pcVer );
void vDbgPortSet( u32 xIndex );
void vDbgPortReset( u32 xIndex );
void vDbgPortToggle( u32 xIndex );
void vDbgPrintf( char *pecFmt, ... );

#undef EXTERN

#endif /* APP_INC_XDEBUG_H_ */
