/**********************************************************************************************************************
 * \file Helper.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Incl.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

unsigned long CLKMicroSecsToTicks(unsigned long usec)
{
    #if (configTICK_RATE_HZ <= 1000)
    {
        UNUSED_PARAMETER(usec);
        return(0);
    }
    #else
    {
        return (usec / portTICK_PERIOD_US);
    }
    #endif
}

unsigned long CLKMilliSecsToTicks(unsigned long msec)
{
    #if (configTICK_RATE_HZ <= 1000)
    {
        return(msec/portTICK_RATE_MS);
    }
    #else
    {
        return ((msec * 1000L) / portTICK_PERIOD_US);
    }
    #endif
}

unsigned long CLKTicksToMilliSecs(unsigned long tick)
{
    #if (configTICK_RATE_HZ <= 1000)
    {
        return (tick * portTICK_RATE_MS) ;
    }
    #else
    {
        return((tick * portTICK_PERIOD_US) / 1000L);
    }
    #endif
}

unsigned long CLKSecondsToTicks(unsigned long sec)
{
    #if (configTICK_RATE_HZ <= 1000)
    {
        return((sec * 1000) / portTICK_RATE_MS);
    }
    #else
    {
        return((sec * 1000000L) / portTICK_PERIOD_US);
    }
    #endif
}

BaseType_t Str2Int(uint8_t *pInputStr, int *iNum)
{
    register int i = 0;
    BaseType_t xRes = 0;
    BaseType_t xVal = 0;

    if (pInputStr[0] == '0' && (pInputStr[1] == 'x' || pInputStr[1] == 'X')) {
        if (pInputStr[2] == '\0')
            return 0;

        for (i = 2; i < 11; i++) {
            if (pInputStr[i] == '\0') {
                *iNum = xVal;
                /* return 1; */
                xRes = 1;
                break;
            }

            if (ISVALIDHEX(pInputStr[i]))
                xVal = (xVal << 4) + CONVERTHEX(pInputStr[i]);
            else {
                /* return 0, Invalid input */
                xRes = 0;
                break;
            }
        }

        /* over 8 digit hex --invalid */
        if (i >= 11)
            xRes = 0;
    }
    /* max 10-digit decimal input */
    else {
        for (i = 0; i < 11; i++) {
            if (pInputStr[i] == '\0')
            {
                *iNum = xVal;
                /* return 1 */
                xRes = 1;
                break;
            }
            else if ((pInputStr[i] == 'k' || pInputStr[i] == 'K') && (i > 0)) {
                xVal = xVal << 10;
                *iNum = xVal;
                xRes = 1;
                break;
            }
            else if ((pInputStr[i] == 'm' || pInputStr[i] == 'M') && (i > 0)) {
                xVal = xVal << 20;
                *iNum = xVal;
                xRes = 1;
                break;
            }
            else if (ISVALIDDEC(pInputStr[i]))
                xVal = xVal * 10 + CONVERTDEC(pInputStr[i]);
            else {
                /* return 0, Invalid input */
                xRes = 0;
                break;
            }
        }

        /* Over 10 digit decimal --invalid */
        if (i >= 11)
            xRes = 0;
    }

    return xRes;
}

void Int2Str(uint8_t *pucStr, int iNum)
{
    register int i;
    register int j = 0;
    BaseType_t xDiv = 1000000000;
    BaseType_t xStatus = 0;

    for(i = 0; i < 10; i++)
    {
        pucStr[j++] = (uint8_t) ((iNum / xDiv) + 48);

        iNum = iNum % xDiv;
        xDiv /= 10;
        if((pucStr[j - 1] == '0') & (xStatus == 0))
        {
            j = 0;
        }
        else
        {
            xStatus++;
        }
    }
}

