/**********************************************************************************************************************
 * \file Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Incl.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

#define _VERSION_       "2.04"
#define HANDLE_INTERRUPT_GLOBALLY()     __enable()

/**
* @brief XCP measurement variable: vehicle speed
* @XCP_Measurement
* @XCP_Comment Vehicle speed
* @XCP_LowerLimit -50
* @XCP_UpperLimit 300
* @XCP_Discrete false
* @XCP_MaxRefreshRate 10
* @XCP_PhysUnit km/h
* @XCP_ConversionFunction
* @XCP_ReadWrite ro
*/
volatile long vehicleSpeed = 100;

/**
* @brief XCP characteristic showcase variable: modifyMe
* @XCP_Characteristic
* @XCP_Comment showcase for XCP characteristic
* @XCP_LowerLimit 0
* @XCP_UpperLimit 255
* @XCP_PhysUnit
* @XCP_StepSize 1
*/
volatile uint8 modifyMe = 5;

int Main(void)
{
    vehicleSpeed = time(0);
    modifyMe = rand();

    HANDLE_INTERRUPT_GLOBALLY();

    vStartDebugTask(_VERSION_);

    // Start the scheduler
    vTaskStartScheduler();

    // The following line should never be reached.
    while(1);

    return -1;
}

void vApplicationTickHook(void)
{
}

void vApplicationIdleHook(void)
{
    // It will be called on each iteration of the idle task.
    // It is essential that code never attempts to block in any way
    __nop();
}

